const test = require('node:test');
const assert = require('node:assert/strict');
require('./helpers');
const db = require('../db');
const management = require('../services/managementService');
const orders = require('../services/orderService');
const { available } = require('../services/couponService');
test('targeted coupons discount only matching menu quantities and retain targets on partial edits', () => {
  const admin = { role: 'admin', id: 1 };
  const menus = db.prepare('SELECT menu_id AS id, price FROM menus WHERE store_id = 1 AND deleted_at IS NULL').all();
  const [first, second] = menus;
  const coupon = management.createCoupon(admin, 1, { title: 'Target test', discountRate: 20, targetMenuId: first.id });
  assert.equal(coupon.targetMenuId, first.id);
  assert.equal(management.updateCoupon(admin, 1, coupon.id, { title: 'Edited' }).targetMenuId, first.id);
  assert.equal(management.listCoupons(admin, 1).find(row => row.id === coupon.id).targetMenuId, first.id);
  const day = new Date(Date.now() + 86400000).toLocaleDateString('sv-SE', { timeZone: 'Asia/Seoul' });
  const body = { storeId: 1, pickupTime: `${day}T12:30`, couponUuid: coupon.uuid, items: [{ menuId: first.id, quantity: 2 }, { menuId: second.id, quantity: 1 }] };
  const result = orders.createOrder(body);
  assert.equal(result.discountAmount, Math.floor(first.price * 2 * .2));
  assert.equal(result.totalPrice, first.price * 2 + second.price - result.discountAmount);
  assert.throws(() => orders.createOrder({ ...body, items: [{ menuId: second.id, quantity: 1 }] }), /target menu/);
  management.updateCoupon(admin, 1, coupon.id, { targetMenuId: 0 });
  const all = orders.createOrder(body);
  assert.equal(all.discountAmount, Math.floor((first.price * 2 + second.price) * .2));
  const other = db.prepare('SELECT menu_id FROM menus WHERE store_id <> 1 LIMIT 1').get().menu_id;
  for (const targetMenuId of [-1, 1.5, '0', null, other, 999999]) assert.throws(() => management.createCoupon(admin, 1, { title: 'Invalid', targetMenuId }), /targetMenuId|Target menu/);
  management.updateCoupon(admin, 1, coupon.id, { targetMenuId: first.id });
  db.prepare("UPDATE menus SET deleted_at = datetime('now') WHERE menu_id = ?").run(first.id);
  assert.equal(available(1, coupon.uuid), undefined);
  db.prepare('UPDATE menus SET deleted_at = NULL WHERE menu_id = ?').run(first.id);
  management.deleteCoupon(admin, 1, coupon.id);
});
